---
env:
  browser: true
  es2021: true
  jquery: true
extends:
  - "airbnb-base"
parserOptions:
  ecmaVersion: "latest"
  sourceType: "module"
rules:
  no-param-reassign:
    - "error"
    - props: false
  quotes: ["error", "double"]
  linebreak-style: ["off"]
