---
IGNORE_GITIGNORED_FILES: true
PRINT_ALPACA: false
JAVASCRIPT_FILTER_REGEX_EXCLUDE: ".*\\.min\\.js"

SPELL_FILTER_REGEX_EXCLUDE: ".*\\.min\\.js|.*\\.dic|.*\\.aff|\\.gitignore"
SPELL_CSPELL_FILTER_REGEX_EXCLUDE: ".*\\.min\\.js|.*\\.dic|.*\\.aff|\\.gitignore"

CSS_FILTER_REGEX_EXCLUDE: ".*\\.min\\.css"

EDITORCONFIG_EDITORCONFIG_CHECKER_FILTER_REGEX_EXCLUDE: "\\.git/.*|.*\\.cs|.*\\.razor|.*\\.dll|.*\\.msg|.*\\.dat|version\\.json|\\.mega-linter\\.yml*"

COPYPASTE_JSCPD_ARGUMENTS: "-k 200 -i \"**/bin/**|**/obj/**|\\.idea/**|node_modules/**|megalinter-reports/**\""

YAML_YAMLLINT_FILTER_REGEX_EXCLUDE: "\\.mega-linter\\.yml"

REPOSITORY_DEVSKIM_ARGUMENTS: "-g **/bin/**,**/obj/**"

MARKDOWN_MARKDOWN_LINK_CHECK_DISABLE_ERRORS: true

EXCLUDED_DIRECTORIES:
  - ".git"

PRE_COMMANDS:
  - command: pip install pydub
    cwd: "workspace"
    venv: pylint        # Will be run at the root of MegaLinter docker image


DISABLE_LINTERS:
  - "SPELL_CSPELL"
  - "JAVASCRIPT_STANDARD"
  - "YAML_PRETTIER"
  - "JAVASCRIPT_PRETTIER"
  - "TYPESCRIPT_PRETTIER"
  - "JSON_PRETTIER"
  - "YAML_V8R"
  - "REPOSITORY_DEVSKIM"

ENABLE_LINTERS:
  - "CSHARP_DOTNET_FORMAT"
  - "BASH_EXEC"
  - "BASH_SHELLCHECK"
  - "BASH_SHFMT"
  - "C_CPPLINT"
  - "CLOJURE_CLJ_KONDO"
  - "COFFEE_COFFEELINT"
  - "CPP_CPPLINT"
  - "DART_DARTANALYZER"
  - "GO_GOLANGCI_LINT"
  - "GO_REVIVE"
  - "GROOVY_NPM_GROOVY_LINT"
  - "JAVA_CHECKSTYLE"
  - "JAVASCRIPT_ES"
  - "JSX_ESLINT"
  - "KOTLIN_KTLINT"
  - "LUA_LUACHECK"
  - "PERL_PERLCRITIC"
  - "PHP_PHPCS"
  - "PHP_PHPSTAN"
  - "PHP_PSALM"
  - "PHP_PHPLINT"
  - "POWERSHELL_POWERSHELL"
  - "PYTHON_PYLINT"
  - "PYTHON_BLACK"
  - "PYTHON_FLAKE8"
  - "PYTHON_ISORT"
  - "PYTHON_BANDIT"
  - "PYTHON_MYPY"
  - "R_LINTR"
  - "RAKU_RAKU"
  - "RUBY_RUBOCOP"
  - "RUST_CLIPPY"
  - "SALESFORCE_SFDX_SCANNER_APEX"
  - "SALESFORCE_SFDX_SCANNER_AURA"
  - "SALESFORCE_SFDX_SCANNER_LWC"
  - "SCALA_SCALAFIX"
  - "SQL_SQL_LINT"
  - "SQL_SQLFLUFF"
  - "SQL_TSQLLINT"
  - "SWIFT_SWIFTLINT"
  - "TSX_ESLINT"
  - "TYPESCRIPT_ES"
  - "VBDOTNET_DOTNET_FORMAT"
  - "CSS_STYLELINT"
  - "CSS_SCSS_LINT"
  - "ENV_DOTENV_LINTER"
  - "GRAPHQL_GRAPHQL_SCHEMA_LINTER"
  - "HTML_HTMLHINT"
  - "JSON_JSONLINT"
  - "JSON_ESLINT_PLUGIN_JSONC"
  - "JSON_V8R"
  - "LATEX_CHKTEX"
  - "MARKDOWN_MARKDOWNLINT"
  - "MARKDOWN_REMARK_LINT"
  - "MARKDOWN_MARKDOWN_LINK_CHECK"
  - "MARKDOWN_MARKDOWN_TABLE_FORMATTER"
  - "PROTOBUF_PROTOLINT"
  - "RST_RST_LINT"
  - "RST_RSTCHECK"
  - "XML_XMLLINT"
  - "YAML_YAMLLINT"
  - "ACTION_ACTIONLINT"
  - "ANSIBLE_ANSIBLE_LINT"
  - "ARM_ARM_TTK"
  - "CLOUDFORMATION_CFN_LINT"
  - "DOCKERFILE_HADOLINT"
  - "EDITORCONFIG_EDITORCONFIG_CHECKER"
  - "GHERKIN_GHERKIN_LINT"
  - "KUBERNETES_KUBEVAL"
  - "KUBERNETES_KUBECONFORM"
  - "OPENAPI_SPECTRAL"
  - "PUPPET_PUPPET_LINT"
  - "SNAKEMAKE_LINT"
  - "SNAKEMAKE_SNAKEFMT"
  - "TEKTON_TEKTON_LINT"
  - "TERRAFORM_TFLINT"
  - "TERRAFORM_TERRASCAN"
  - "TERRAFORM_TERRAGRUNT"
  - "TERRAFORM_TERRAFORM_FMT"
  - "TERRAFORM_CHECKOV"
  - "TERRAFORM_KICS"
  - "COPYPASTE_JSCPD"
  - "REPOSITORY_DUSTILOCK"
  - "REPOSITORY_GIT_DIFF"
  - "REPOSITORY_GITLEAKS"
  - "REPOSITORY_GOODCHECK"
  - "REPOSITORY_SECRETLINT"
  - "REPOSITORY_SEMGREP"
  - "REPOSITORY_SYFT"
  - "REPOSITORY_TRIVY"
  - "SPELL_MISSPELL"
